### ISSUE TITLE
Api.GetLicense call causes CallbackOnCollectedDelegate MDA error in .NET 4.7.2

### ISSUE THREAD

**Issue by SteffanDonal** [ViveportSoftware/viveport_sdk_csharp#5]
```
Managed Debugging Assistant 'CallbackOnCollectedDelegate' 
  Message=Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'Viveport!Viveport.Internal.GetLicenseCallback::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'
```

The above error is prompted after calling `Api.GetLicense`, reliably - the license checker that was passed into the function is kept in a static readonly property, and so shouldn't be the cause of the error.

This prevents DRM checking from working in .NET applications!

**Comment by Jake1006** [comment]
@SteffanDonal Can this commit solve your problem? We can not reproduce this issue. Could you please try this commit first? Thank you!

**Comment by SteffanDonal** [comment]
Hey @Jake1006 - Can the fix be published as a prerelease version on nuget so I can upgrade?

**Comment by Jake1006** [comment]
@SteffanDonal 
Please try this
[https://www.myget.org/feed/viveportsoftware/package/nuget/Viveport](https://www.myget.org/feed/viveportsoftware/package/nuget/Viveport)
Thank you

**Comment by SteffanDonal** [comment]
I can confirm there's no GC / MDA error anymore! Thank you 😉
